import type { Metadata } from "next"
import { Inter } from "next/font/google"

import "./globals.css"

import { cn } from "@/libs/utils"

import { ReactQueryProvider } from "@/components/providers/react-query-provider"
import { ToasterProvider } from "@/components/providers/toaster"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <ReactQueryProvider>
        <body
          className={cn(
            inter.className,
            "bg-background min-h-screen antialiased"
          )}
        >
          {children}
          <ToasterProvider />
        </body>
      </ReactQueryProvider>
    </html>
  )
}
