// <auto-generated />
using System;
using ArtLite.Api.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ArtLite.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231215063915_FirstMigrations")]
    partial class FirstMigrations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ArtLite.Api.Entities.Artwork", b =>
                {
                    b.Property<Guid>("IdArtwork")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasComputedColumnSql("GETDATE()");

                    b.HasKey("IdArtwork");

                    b.HasIndex("CreatorId");

                    b.ToTable("Artworks");

                    b.HasData(
                        new
                        {
                            IdArtwork = new Guid("7443d740-b827-47dd-9d92-0dff40042228"),
                            CreatedAt = new DateTime(2023, 10, 20, 16, 9, 58, 488, DateTimeKind.Local).AddTicks(9475),
                            CreatorId = new Guid("d53570c7-8651-4fc6-9cce-15848be6f289"),
                            Description = "Iusto quia inventore voluptas expedita laborum eum omnis occaecati. Qui nihil aperiam assumenda eveniet autem. Vel sit libero rerum animi.",
                            Title = "3D Character",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            IdArtwork = new Guid("1cd4cc4a-4a4a-4eb8-92b7-036a4e3d5520"),
                            CreatedAt = new DateTime(2023, 8, 2, 23, 46, 6, 136, DateTimeKind.Local).AddTicks(7502),
                            CreatorId = new Guid("d53570c7-8651-4fc6-9cce-15848be6f289"),
                            Description = "Possimus facilis quia sed ipsum officiis qui qui molestias. Doloremque ea id voluptates facere fugiat fugiat. Rerum atque quibusdam. Non fugiat voluptatem qui nisi sunt. Qui rerum rerum praesentium molestiae hic iure. Ea quia et iste excepturi nesciunt.",
                            Title = "Pirate",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            IdArtwork = new Guid("edb8d3de-3a0e-4149-ad04-7b82c14eca57"),
                            CreatedAt = new DateTime(2023, 3, 1, 9, 48, 41, 270, DateTimeKind.Local).AddTicks(4084),
                            CreatorId = new Guid("d53570c7-8651-4fc6-9cce-15848be6f289"),
                            Description = "Consequatur sit quo quos sint officia. Dolore eius consequatur harum ratione earum consequatur. Commodi iure voluptatum et quia molestiae quis ut natus voluptatem. Pariatur facere et nihil id. Saepe sit et. Tempore a nulla et eveniet enim exercitationem.",
                            Title = "Tribal Mage",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            IdArtwork = new Guid("ca8d3891-f868-4da0-8774-29b259eb5c8f"),
                            CreatedAt = new DateTime(2023, 1, 26, 11, 54, 20, 489, DateTimeKind.Local).AddTicks(2317),
                            CreatorId = new Guid("d53570c7-8651-4fc6-9cce-15848be6f289"),
                            Description = "Quisquam veritatis sequi tempora et quod dolor. Quibusdam harum laborum. Molestiae necessitatibus nisi est molestiae. Sit enim et asperiores voluptatum dolorem voluptas laudantium. Quia minima et et hic aut et sed omnis occaecati. Animi officiis sed corporis dolores nesciunt quia quia.",
                            Title = "Joel - Pedro Pascal",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            IdArtwork = new Guid("932a65c4-ee3f-4b71-96ec-4b132b7c505e"),
                            CreatedAt = new DateTime(2023, 12, 14, 0, 19, 7, 246, DateTimeKind.Local).AddTicks(2812),
                            CreatorId = new Guid("d53570c7-8651-4fc6-9cce-15848be6f289"),
                            Description = "Rem eveniet est officia voluptas eum omnis illum expedita est. Eum nam eos nihil. Autem dolorem optio accusantium nemo consectetur enim dolores. Cumque libero culpa rerum voluptas.",
                            Title = "Goblin",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            IdArtwork = new Guid("bb6aace8-b87f-4789-9f87-9f61da57ae72"),
                            CreatedAt = new DateTime(2022, 12, 25, 1, 11, 5, 137, DateTimeKind.Local).AddTicks(7946),
                            CreatorId = new Guid("d53570c7-8651-4fc6-9cce-15848be6f289"),
                            Description = "Ut dolorem illo laudantium. Sit sit praesentium aperiam praesentium ut quos. Nam ad in. Qui incidunt ut fuga porro. Non vel quisquam ut. Animi et qui non eum.",
                            Title = "Orc Lady",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            IdArtwork = new Guid("6d4facd0-299c-4d96-835e-b3fad8986c5a"),
                            CreatedAt = new DateTime(2023, 11, 13, 20, 6, 0, 997, DateTimeKind.Local).AddTicks(2065),
                            CreatorId = new Guid("d53570c7-8651-4fc6-9cce-15848be6f289"),
                            Description = "Harum sed ut aliquid. Mollitia tempora quos ex perferendis et optio similique et fuga. Est vero molestiae. Eos provident rerum. Nam eos ipsam quasi. Omnis at et veniam eum.",
                            Title = "Lemmy",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            IdArtwork = new Guid("55b6cc08-d79d-4485-81c6-07ed39c064e5"),
                            CreatedAt = new DateTime(2023, 5, 29, 7, 19, 57, 919, DateTimeKind.Local).AddTicks(2814),
                            CreatorId = new Guid("d53570c7-8651-4fc6-9cce-15848be6f289"),
                            Description = "Odit ratione aut. Magni ea quisquam culpa magni vitae officiis id maiores vel. Deleniti voluptate nobis. Veniam sequi dolorem et neque quia esse sit perspiciatis.",
                            Title = "WoW Gnome Warrior",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            IdArtwork = new Guid("387ca2ab-87ef-4613-8039-58986ecb4e7c"),
                            CreatedAt = new DateTime(2023, 1, 2, 5, 7, 16, 199, DateTimeKind.Local).AddTicks(2746),
                            CreatorId = new Guid("d53570c7-8651-4fc6-9cce-15848be6f289"),
                            Description = "Deserunt quos adipisci rem voluptatibus sit exercitationem consequatur. Mollitia maiores omnis quasi voluptatem hic earum nisi facilis autem. Eius dolor doloremque qui eveniet nulla et dicta. Impedit est et sequi accusantium est nam aut. Sit nulla sed dolor iste.",
                            Title = "Knight fanart from Priston",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            IdArtwork = new Guid("c25e263a-1ac6-4f26-867a-43deaa3f8f26"),
                            CreatedAt = new DateTime(2023, 2, 25, 0, 38, 38, 303, DateTimeKind.Local).AddTicks(5092),
                            CreatorId = new Guid("d53570c7-8651-4fc6-9cce-15848be6f289"),
                            Description = "Esse praesentium quibusdam sunt dolores quo non. Ad hic maxime fuga quae suscipit. Delectus perferendis praesentium hic mollitia. Dolorum vitae est. Rerum sint dolores vel libero blanditiis. Suscipit excepturi enim sed dolor possimus quae magni voluptates.",
                            Title = "Fighter from Priston Tale",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            IdArtwork = new Guid("5da4c9ae-86df-4632-8ffa-865d7a20b425"),
                            CreatedAt = new DateTime(2023, 12, 4, 11, 9, 40, 350, DateTimeKind.Local).AddTicks(9315),
                            CreatorId = new Guid("d53570c7-8651-4fc6-9cce-15848be6f289"),
                            Description = "Doloremque qui quam modi rem quibusdam vel ratione beatae. Velit architecto natus est quos. Nostrum sed veritatis vitae temporibus aliquam esse qui est. Laboriosam vitae facilis porro. Facere rem ut quidem est blanditiis fugit ipsa rem dolorem.",
                            Title = "Pike Man",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            IdArtwork = new Guid("05e8dad6-4683-4e79-acdc-bceada8b55a6"),
                            CreatedAt = new DateTime(2023, 5, 10, 12, 58, 18, 857, DateTimeKind.Local).AddTicks(9998),
                            CreatorId = new Guid("d53570c7-8651-4fc6-9cce-15848be6f289"),
                            Description = "Culpa inventore omnis ipsam mollitia sed incidunt praesentium. Et commodi ad dignissimos id. Aut assumenda quam dolor quos officia quaerat. In dolorum necessitatibus at repellat libero sunt sint tempora.",
                            Title = "Mechanician",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            IdArtwork = new Guid("5d2961ef-985f-44e4-93f0-5a563bb4ef62"),
                            CreatedAt = new DateTime(2023, 5, 24, 10, 36, 13, 738, DateTimeKind.Local).AddTicks(1783),
                            CreatorId = new Guid("d53570c7-8651-4fc6-9cce-15848be6f289"),
                            Description = "Culpa consequatur perferendis cupiditate non ipsam sint corrupti incidunt. Optio quod quo enim aut aut voluptatem ullam. Optio nihil soluta ut. Est maiores eos cum iure quo nobis fugit ea.",
                            Title = "Atalanta",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            IdArtwork = new Guid("24234d88-d57a-4a89-af74-999672025fc1"),
                            CreatedAt = new DateTime(2023, 10, 24, 9, 2, 25, 827, DateTimeKind.Local).AddTicks(2588),
                            CreatorId = new Guid("d53570c7-8651-4fc6-9cce-15848be6f289"),
                            Description = "Aut fugiat aut sint porro. Sunt laborum distinctio quo voluptatem eveniet sunt tempora et ut. Voluptas aspernatur occaecati sapiente. Eum voluptatem quo velit sed officia et. Deserunt nemo illo rerum illum necessitatibus sit eius sapiente ducimus.",
                            Title = "Goblins",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            IdArtwork = new Guid("c809a906-01f9-4eee-bd68-1a7e46e97b21"),
                            CreatedAt = new DateTime(2023, 7, 31, 5, 39, 19, 805, DateTimeKind.Local).AddTicks(4921),
                            CreatorId = new Guid("d53570c7-8651-4fc6-9cce-15848be6f289"),
                            Description = "Ut non eligendi. Voluptatem ullam odit. Reprehenderit qui et sed sint ea. Perspiciatis quisquam sed nulla voluptas est voluptate repudiandae ea a. Et autem necessitatibus quia id quod perferendis sunt consectetur expedita.",
                            Title = "Stylized Cyclops",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("ArtLite.Api.Entities.Creator", b =>
                {
                    b.Property<Guid>("IdCreator")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Biography")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("HighlightedPhrase")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileBanner")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SocialFacebook")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SocialFigma")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SocialInstagram")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SocialLinkedin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SocialYoutube")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasComputedColumnSql("GETDATE()");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IdCreator");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Creators");

                    b.HasData(
                        new
                        {
                            IdCreator = new Guid("d53570c7-8651-4fc6-9cce-15848be6f289"),
                            Biography = "3D Character Artist. I have a passion for 3D art. Currently working on my own personal projects!",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sebas@gmail.com",
                            HighlightedPhrase = "3D Character Artist",
                            ProfileBanner = "https://cdna.artstation.com/p/users/covers/000/583/624/default/73c0b86e24cfe09e6954896a1b24b5c0.jpg?1687826140",
                            ProfileImage = "https://cdna.artstation.com/p/users/avatars/000/583/624/large/21ab51c6fdec0656327acd1decc6b95f.jpg?1521491898",
                            Slug = "sebastian_cavazzoli",
                            SocialFacebook = "",
                            SocialFigma = "",
                            SocialInstagram = "https://www.instagram.com/sebacavazzoli.art",
                            SocialLinkedin = "",
                            SocialYoutube = "https://www.youtube.com/sebastiancavazzoli",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "Sebastian Cavazzoli"
                        });
                });

            modelBuilder.Entity("ArtLite.Api.Entities.Image", b =>
                {
                    b.Property<Guid>("IdImage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ArtworkId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CloudId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Src")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdImage");

                    b.HasIndex("ArtworkId");

                    b.HasIndex("Order", "ArtworkId")
                        .IsUnique();

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            IdImage = new Guid("2fabb156-fe75-4908-baf4-59fdf2e08dbb"),
                            ArtworkId = new Guid("7443d740-b827-47dd-9d92-0dff40042228"),
                            CloudId = "",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Order = 1,
                            Src = "https://cdnb.artstation.com/p/assets/images/images/070/397/485/20231212212844/smaller_square/sebastian-cavazzoli-2313313.jpg?1702438125"
                        },
                        new
                        {
                            IdImage = new Guid("c97c7945-a60d-411b-862f-0bb57ba76fb2"),
                            ArtworkId = new Guid("7443d740-b827-47dd-9d92-0dff40042228"),
                            CloudId = "",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Order = 2,
                            Src = "https://cdnb.artstation.com/p/assets/images/images/070/397/365/large/sebastian-cavazzoli-yishu.jpg?1702437714"
                        },
                        new
                        {
                            IdImage = new Guid("21430ea5-79a8-48d3-a68d-8ae4b619f437"),
                            ArtworkId = new Guid("7443d740-b827-47dd-9d92-0dff40042228"),
                            CloudId = "",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Order = 3,
                            Src = "https://cdnb.artstation.com/p/assets/images/images/070/397/407/large/sebastian-cavazzoli-pp.jpg?1702437814"
                        },
                        new
                        {
                            IdImage = new Guid("5bbba578-9a85-45d6-acf2-c336ab152287"),
                            ArtworkId = new Guid("7443d740-b827-47dd-9d92-0dff40042228"),
                            CloudId = "",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Order = 4,
                            Src = "https://cdnb.artstation.com/p/assets/images/images/070/397/349/large/sebastian-cavazzoli-19.jpg?1702437673"
                        },
                        new
                        {
                            IdImage = new Guid("2aca330c-16f8-4b12-bc80-165ef0b617b3"),
                            ArtworkId = new Guid("7443d740-b827-47dd-9d92-0dff40042228"),
                            CloudId = "",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Order = 5,
                            Src = "https://cdna.artstation.com/p/assets/images/images/070/397/400/large/sebastian-cavazzoli-2.jpg?1702437799"
                        },
                        new
                        {
                            IdImage = new Guid("e21e1616-3d68-49ed-8299-c5068b051cd6"),
                            ArtworkId = new Guid("7443d740-b827-47dd-9d92-0dff40042228"),
                            CloudId = "",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Order = 6,
                            Src = "https://cdna.artstation.com/p/assets/images/images/070/397/586/large/sebastian-cavazzoli-refe.jpg?1702438347"
                        },
                        new
                        {
                            IdImage = new Guid("65890ea8-dd41-448c-a540-c6f7e7d7eac9"),
                            ArtworkId = new Guid("1cd4cc4a-4a4a-4eb8-92b7-036a4e3d5520"),
                            CloudId = "",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Order = 1,
                            Src = "https://cdnb.artstation.com/p/assets/images/images/064/384/223/smaller_square/sebastian-cavazzoli-1.jpg?1687806929"
                        },
                        new
                        {
                            IdImage = new Guid("88e1c6de-213b-4273-b82a-1acff0c0e8e3"),
                            ArtworkId = new Guid("1cd4cc4a-4a4a-4eb8-92b7-036a4e3d5520"),
                            CloudId = "",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Order = 2,
                            Src = "https://cdna.artstation.com/p/assets/images/images/064/384/238/large/sebastian-cavazzoli-new-project.jpg?1687806957"
                        },
                        new
                        {
                            IdImage = new Guid("7da95963-27b5-4b31-bef8-d038a503d2c6"),
                            ArtworkId = new Guid("1cd4cc4a-4a4a-4eb8-92b7-036a4e3d5520"),
                            CloudId = "",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Order = 3,
                            Src = "https://cdnb.artstation.com/p/assets/images/images/064/384/233/large/sebastian-cavazzoli-2.jpg?1687806944"
                        },
                        new
                        {
                            IdImage = new Guid("e3093a5a-c324-4f19-a5b6-879e971a6853"),
                            ArtworkId = new Guid("edb8d3de-3a0e-4149-ad04-7b82c14eca57"),
                            CloudId = "",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Order = 1,
                            Src = "https://cdnb.artstation.com/p/assets/video_clips/images/066/131/241/smaller_square/sebastian-cavazzoli-thumb.jpg?1692121620"
                        },
                        new
                        {
                            IdImage = new Guid("1a844055-ff4f-441c-ae38-e9786aeccfc1"),
                            ArtworkId = new Guid("edb8d3de-3a0e-4149-ad04-7b82c14eca57"),
                            CloudId = "",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Order = 2,
                            Src = "https://cdnb.artstation.com/p/assets/images/images/066/131/231/large/sebastian-cavazzoli-asset.jpg?1692121609"
                        },
                        new
                        {
                            IdImage = new Guid("5e54116b-5189-44f0-874b-9dee8542bc9d"),
                            ArtworkId = new Guid("edb8d3de-3a0e-4149-ad04-7b82c14eca57"),
                            CloudId = "",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Order = 3,
                            Src = "https://cdna.artstation.com/p/assets/images/images/066/131/236/large/sebastian-cavazzoli-asset.jpg?1692121615"
                        },
                        new
                        {
                            IdImage = new Guid("9dd37231-29bb-47ad-a544-fb5ee1b48e91"),
                            ArtworkId = new Guid("edb8d3de-3a0e-4149-ad04-7b82c14eca57"),
                            CloudId = "",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Order = 4,
                            Src = "https://cdnb.artstation.com/p/assets/images/images/066/131/243/large/sebastian-cavazzoli-asset.jpg?1692121624"
                        },
                        new
                        {
                            IdImage = new Guid("66e5ad65-7831-4601-ba97-d439550382ba"),
                            ArtworkId = new Guid("ca8d3891-f868-4da0-8774-29b259eb5c8f"),
                            CloudId = "",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Order = 1,
                            Src = "https://cdnb.artstation.com/p/assets/images/images/062/527/639/smaller_square/sebastian-cavazzoli-04a4ddc0-1c5c-42a3-b4ff-5e8c77014ad4.jpg?1683333990"
                        },
                        new
                        {
                            IdImage = new Guid("8e34ee02-737d-4244-a70e-d5bb95dfcd44"),
                            ArtworkId = new Guid("ca8d3891-f868-4da0-8774-29b259eb5c8f"),
                            CloudId = "",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Order = 2,
                            Src = "https://cdna.artstation.com/p/assets/images/images/062/527/640/large/sebastian-cavazzoli-e3254524-8134-45f8-a5d7-12f489f95e4b.jpg?1683333994"
                        },
                        new
                        {
                            IdImage = new Guid("24a6844a-2581-49e5-9a15-2d7ba7099566"),
                            ArtworkId = new Guid("ca8d3891-f868-4da0-8774-29b259eb5c8f"),
                            CloudId = "",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Order = 3,
                            Src = "https://cdna.artstation.com/p/assets/images/images/062/527/642/large/sebastian-cavazzoli-f9ed5505-2e92-4e7c-af18-d1d770e747b6.jpg?1683333998"
                        },
                        new
                        {
                            IdImage = new Guid("15fff774-816b-436f-81f5-d863bbf11fdb"),
                            ArtworkId = new Guid("932a65c4-ee3f-4b71-96ec-4b132b7c505e"),
                            CloudId = "",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Order = 1,
                            Src = "https://cdnb.artstation.com/p/assets/images/images/058/444/123/smaller_square/sebastian-cavazzoli-1b.jpg?1674161052"
                        },
                        new
                        {
                            IdImage = new Guid("d810d6a5-5b2f-4529-abca-5fac0f108471"),
                            ArtworkId = new Guid("932a65c4-ee3f-4b71-96ec-4b132b7c505e"),
                            CloudId = "",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Order = 2,
                            Src = "https://cdnb.artstation.com/p/assets/images/images/058/444/135/large/sebastian-cavazzoli-2b.jpg?1674161070"
                        },
                        new
                        {
                            IdImage = new Guid("bf660dd8-2182-422d-a50d-addbd1fccff9"),
                            ArtworkId = new Guid("932a65c4-ee3f-4b71-96ec-4b132b7c505e"),
                            CloudId = "",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Order = 3,
                            Src = "https://cdna.artstation.com/p/assets/images/images/058/444/254/large/sebastian-cavazzoli-asd.jpg?1674161336"
                        },
                        new
                        {
                            IdImage = new Guid("3760d0ec-1d32-4eeb-9f94-0425edaca600"),
                            ArtworkId = new Guid("bb6aace8-b87f-4789-9f87-9f61da57ae72"),
                            CloudId = "",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Order = 1,
                            Src = "https://cdnb.artstation.com/p/assets/images/images/055/727/009/smaller_square/sebastian-cavazzoli-1.jpg?1667597373"
                        },
                        new
                        {
                            IdImage = new Guid("464c98da-8f53-43a4-ad15-74878a226beb"),
                            ArtworkId = new Guid("bb6aace8-b87f-4789-9f87-9f61da57ae72"),
                            CloudId = "",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Order = 2,
                            Src = "https://cdna.artstation.com/p/assets/images/images/055/726/896/large/sebastian-cavazzoli-2.jpg?1667597123"
                        },
                        new
                        {
                            IdImage = new Guid("50820e84-cfb8-4f22-9a3a-28912b1d10f9"),
                            ArtworkId = new Guid("bb6aace8-b87f-4789-9f87-9f61da57ae72"),
                            CloudId = "",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Order = 3,
                            Src = "https://cdnb.artstation.com/p/assets/images/images/055/726/901/large/sebastian-cavazzoli-refe.jpg?1667597131"
                        },
                        new
                        {
                            IdImage = new Guid("2cac06a9-08ec-487b-98c7-a10eeef10250"),
                            ArtworkId = new Guid("6d4facd0-299c-4d96-835e-b3fad8986c5a"),
                            CloudId = "",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Order = 1,
                            Src = "https://cdnb.artstation.com/p/assets/covers/images/052/375/327/20220807090628/smaller_square/sebastian-cavazzoli-sebastian-cavazzoli-cheloportada2.jpg?1659881189"
                        },
                        new
                        {
                            IdImage = new Guid("ead7fa71-6088-42d7-96ba-2ee34118b25e"),
                            ArtworkId = new Guid("55b6cc08-d79d-4485-81c6-07ed39c064e5"),
                            CloudId = "",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Order = 1,
                            Src = "https://cdna.artstation.com/p/assets/video_clips/images/045/020/050/smaller_square/sebastian-cavazzoli-thumb.jpg?1641742817"
                        },
                        new
                        {
                            IdImage = new Guid("d125ad1e-92c0-40f7-ab32-2d40caf34a29"),
                            ArtworkId = new Guid("55b6cc08-d79d-4485-81c6-07ed39c064e5"),
                            CloudId = "",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Order = 2,
                            Src = "https://cdna.artstation.com/p/assets/images/images/045/020/000/large/sebastian-cavazzoli-1-4.jpg?1641742734"
                        },
                        new
                        {
                            IdImage = new Guid("ea3e1123-c391-4e8d-8cb7-e8e54bad5155"),
                            ArtworkId = new Guid("55b6cc08-d79d-4485-81c6-07ed39c064e5"),
                            CloudId = "",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Order = 3,
                            Src = "https://cdna.artstation.com/p/assets/images/images/045/019/996/large/sebastian-cavazzoli-3b-3.jpg?1641742715"
                        },
                        new
                        {
                            IdImage = new Guid("a03c1514-62c3-450e-9959-1f4c89bde650"),
                            ArtworkId = new Guid("55b6cc08-d79d-4485-81c6-07ed39c064e5"),
                            CloudId = "",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Order = 4,
                            Src = "https://cdna.artstation.com/p/assets/images/images/045/019/990/large/sebastian-cavazzoli-4-6.jpg?1641742699"
                        },
                        new
                        {
                            IdImage = new Guid("0f289f84-becb-4f28-9f5e-573ccbe1e601"),
                            ArtworkId = new Guid("387ca2ab-87ef-4613-8039-58986ecb4e7c"),
                            CloudId = "",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Order = 1,
                            Src = "https://cdna.artstation.com/p/assets/covers/images/037/967/798/smaller_square/sebastian-cavazzoli-sebastian-cavazzoli-3.jpg?1621816194"
                        },
                        new
                        {
                            IdImage = new Guid("e8834e14-aec6-44f8-93c0-7edf44b497ea"),
                            ArtworkId = new Guid("387ca2ab-87ef-4613-8039-58986ecb4e7c"),
                            CloudId = "",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Order = 2,
                            Src = "https://cdnb.artstation.com/p/assets/images/images/037/967/575/large/sebastian-cavazzoli-1b.jpg?1621815282"
                        },
                        new
                        {
                            IdImage = new Guid("f375b523-f003-414a-8112-e5c1225c2e83"),
                            ArtworkId = new Guid("387ca2ab-87ef-4613-8039-58986ecb4e7c"),
                            CloudId = "",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Order = 3,
                            Src = "https://cdna.artstation.com/p/assets/images/images/037/967/578/large/sebastian-cavazzoli-3.jpg?1621815288"
                        },
                        new
                        {
                            IdImage = new Guid("a2e1dc6c-fbfe-4975-98e4-f13774448a02"),
                            ArtworkId = new Guid("387ca2ab-87ef-4613-8039-58986ecb4e7c"),
                            CloudId = "",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Order = 4,
                            Src = "https://cdna.artstation.com/p/assets/images/images/037/967/552/large/sebastian-cavazzoli-4.jpg?1621815193"
                        },
                        new
                        {
                            IdImage = new Guid("a8949f0e-7e05-4c65-8e43-e477a3acb3d7"),
                            ArtworkId = new Guid("387ca2ab-87ef-4613-8039-58986ecb4e7c"),
                            CloudId = "",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Order = 5,
                            Src = "https://cdna.artstation.com/p/assets/images/images/037/967/556/large/sebastian-cavazzoli-6.jpg?1621815211"
                        },
                        new
                        {
                            IdImage = new Guid("7fdce895-c16b-4de9-b0ae-76355da86874"),
                            ArtworkId = new Guid("387ca2ab-87ef-4613-8039-58986ecb4e7c"),
                            CloudId = "",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Order = 6,
                            Src = "https://cdnb.artstation.com/p/assets/images/images/037/967/559/large/sebastian-cavazzoli-7.jpg?1621815223"
                        },
                        new
                        {
                            IdImage = new Guid("1b28b012-2cf5-4526-be03-34b09774633d"),
                            ArtworkId = new Guid("387ca2ab-87ef-4613-8039-58986ecb4e7c"),
                            CloudId = "",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Order = 7,
                            Src = "https://cdnb.artstation.com/p/assets/images/images/037/967/571/large/sebastian-cavazzoli-b2b.jpg?1621815273"
                        },
                        new
                        {
                            IdImage = new Guid("62765a44-f0dd-4c1c-b53e-81c3c0b186d2"),
                            ArtworkId = new Guid("387ca2ab-87ef-4613-8039-58986ecb4e7c"),
                            CloudId = "",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Order = 8,
                            Src = "https://cdnb.artstation.com/p/assets/images/images/037/967/569/large/sebastian-cavazzoli-b1.jpg?1621815262"
                        },
                        new
                        {
                            IdImage = new Guid("41fd76e3-ea0b-4c96-8d9c-8c825c103ce2"),
                            ArtworkId = new Guid("c25e263a-1ac6-4f26-867a-43deaa3f8f26"),
                            CloudId = "",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Order = 1,
                            Src = "https://cdna.artstation.com/p/assets/images/images/036/831/246/20210418093453/smaller_square/sebastian-cavazzoli-widefsnew.jpg?1618756493"
                        },
                        new
                        {
                            IdImage = new Guid("7b9ecd46-5894-4c1b-ba3a-fc56c9d60a88"),
                            ArtworkId = new Guid("c25e263a-1ac6-4f26-867a-43deaa3f8f26"),
                            CloudId = "",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Order = 2,
                            Src = "https://cdna.artstation.com/p/assets/images/images/036/831/246/large/sebastian-cavazzoli-widefsnew.jpg?1618756493"
                        },
                        new
                        {
                            IdImage = new Guid("addfbe23-6974-40ef-b14b-9e4bb3f64339"),
                            ArtworkId = new Guid("c25e263a-1ac6-4f26-867a-43deaa3f8f26"),
                            CloudId = "",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Order = 3,
                            Src = "https://cdna.artstation.com/p/assets/images/images/035/765/826/large/sebastian-cavazzoli-0.jpg?1615841303"
                        },
                        new
                        {
                            IdImage = new Guid("41f40471-c64f-42ad-9601-9abcba031961"),
                            ArtworkId = new Guid("c25e263a-1ac6-4f26-867a-43deaa3f8f26"),
                            CloudId = "",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Order = 4,
                            Src = "https://cdnb.artstation.com/p/assets/images/images/035/766/297/large/sebastian-cavazzoli-5.jpg?1615842190"
                        },
                        new
                        {
                            IdImage = new Guid("442886e3-dff9-49f7-bc3c-63b4649b0b13"),
                            ArtworkId = new Guid("c25e263a-1ac6-4f26-867a-43deaa3f8f26"),
                            CloudId = "",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Order = 5,
                            Src = "https://cdnb.artstation.com/p/assets/images/images/035/765/867/large/sebastian-cavazzoli-3b.jpg?1615841338"
                        },
                        new
                        {
                            IdImage = new Guid("161d0c07-45dd-480a-97d8-c1c9246003df"),
                            ArtworkId = new Guid("c25e263a-1ac6-4f26-867a-43deaa3f8f26"),
                            CloudId = "",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Order = 6,
                            Src = "https://cdnb.artstation.com/p/assets/images/images/035/765/851/large/sebastian-cavazzoli-2.jpg?1615841326"
                        },
                        new
                        {
                            IdImage = new Guid("e0bfd700-662f-4242-ac0f-250d9b0eaaaa"),
                            ArtworkId = new Guid("c25e263a-1ac6-4f26-867a-43deaa3f8f26"),
                            CloudId = "",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Order = 7,
                            Src = "https://cdna.artstation.com/p/assets/images/images/035/765/840/large/sebastian-cavazzoli-1b.jpg?1615841315"
                        },
                        new
                        {
                            IdImage = new Guid("af951a97-3b76-4fc6-9bc7-9a68a15dee7f"),
                            ArtworkId = new Guid("c25e263a-1ac6-4f26-867a-43deaa3f8f26"),
                            CloudId = "",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Order = 8,
                            Src = "https://cdna.artstation.com/p/assets/images/images/035/765/882/large/sebastian-cavazzoli-back.jpg?1615841349"
                        },
                        new
                        {
                            IdImage = new Guid("f91d62ce-1e88-4577-a059-df8e14a1095c"),
                            ArtworkId = new Guid("c25e263a-1ac6-4f26-867a-43deaa3f8f26"),
                            CloudId = "",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Order = 9,
                            Src = "https://cdnb.artstation.com/p/assets/images/images/035/426/297/large/sebastian-cavazzoli-1.jpg?1614916297"
                        },
                        new
                        {
                            IdImage = new Guid("5f540320-1ddc-4302-9c29-948fd0291667"),
                            ArtworkId = new Guid("5da4c9ae-86df-4632-8ffa-865d7a20b425"),
                            CloudId = "",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Order = 1,
                            Src = "https://cdnb.artstation.com/p/assets/images/images/038/143/017/smaller_square/sebastian-cavazzoli-7.jpg?1622294979"
                        },
                        new
                        {
                            IdImage = new Guid("78f20fe9-10bf-4ec5-a778-732916542fa7"),
                            ArtworkId = new Guid("5da4c9ae-86df-4632-8ffa-865d7a20b425"),
                            CloudId = "",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Order = 2,
                            Src = "https://cdnb.artstation.com/p/assets/images/images/038/142/989/large/sebastian-cavazzoli-2.jpg?1622294909"
                        },
                        new
                        {
                            IdImage = new Guid("df46542c-ca14-4f1e-8be6-a3a72c5101cc"),
                            ArtworkId = new Guid("5da4c9ae-86df-4632-8ffa-865d7a20b425"),
                            CloudId = "",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Order = 3,
                            Src = "https://cdnb.artstation.com/p/assets/images/images/038/142/995/large/sebastian-cavazzoli-3.jpg?1622294923"
                        },
                        new
                        {
                            IdImage = new Guid("43c01fe3-6638-446d-b0bc-3c093ab65ff8"),
                            ArtworkId = new Guid("5da4c9ae-86df-4632-8ffa-865d7a20b425"),
                            CloudId = "",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Order = 4,
                            Src = "https://cdnb.artstation.com/p/assets/images/images/038/142/999/large/sebastian-cavazzoli-4.jpg?1622294937"
                        },
                        new
                        {
                            IdImage = new Guid("8edb9817-a17c-44f6-a3f0-20fabd49eb03"),
                            ArtworkId = new Guid("5da4c9ae-86df-4632-8ffa-865d7a20b425"),
                            CloudId = "",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Order = 5,
                            Src = "https://cdnb.artstation.com/p/assets/images/images/038/154/939/large/sebastian-cavazzoli-a.jpg?1622324011"
                        },
                        new
                        {
                            IdImage = new Guid("82d84326-df69-45a6-8118-2a3e98a94596"),
                            ArtworkId = new Guid("5da4c9ae-86df-4632-8ffa-865d7a20b425"),
                            CloudId = "",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Order = 6,
                            Src = "https://cdnb.artstation.com/p/assets/images/images/038/143/019/large/sebastian-cavazzoli-9.jpg?1622294992"
                        },
                        new
                        {
                            IdImage = new Guid("8f94c39a-2db4-4691-baa1-c7e522fb91ac"),
                            ArtworkId = new Guid("5da4c9ae-86df-4632-8ffa-865d7a20b425"),
                            CloudId = "",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Order = 7,
                            Src = "https://cdnb.artstation.com/p/assets/images/images/038/143/029/large/sebastian-cavazzoli-wide2.jpg?1622295012"
                        },
                        new
                        {
                            IdImage = new Guid("46a3b6ae-65b1-4ff0-8ef6-bc96b27f256a"),
                            ArtworkId = new Guid("05e8dad6-4683-4e79-acdc-bceada8b55a6"),
                            CloudId = "",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Order = 1,
                            Src = "https://cdnb.artstation.com/p/assets/images/images/070/397/631/smaller_square/sebastian-cavazzoli-close2.jpg?1702438582"
                        },
                        new
                        {
                            IdImage = new Guid("bc18a641-f130-4e05-b159-9950439f863f"),
                            ArtworkId = new Guid("05e8dad6-4683-4e79-acdc-bceada8b55a6"),
                            CloudId = "",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Order = 2,
                            Src = "https://cdna.artstation.com/p/assets/images/images/070/397/762/large/sebastian-cavazzoli-clay1.jpg?1702439021"
                        },
                        new
                        {
                            IdImage = new Guid("00a0d4d7-9d86-47c7-a54a-ffa5b82bd515"),
                            ArtworkId = new Guid("05e8dad6-4683-4e79-acdc-bceada8b55a6"),
                            CloudId = "",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Order = 3,
                            Src = "https://cdnb.artstation.com/p/assets/images/images/070/397/767/large/sebastian-cavazzoli-clay2.jpg?1702439029"
                        },
                        new
                        {
                            IdImage = new Guid("35301d7d-06f3-4caa-b1b8-591fa911a215"),
                            ArtworkId = new Guid("5d2961ef-985f-44e4-93f0-5a563bb4ef62"),
                            CloudId = "",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Order = 1,
                            Src = "https://cdna.artstation.com/p/assets/covers/images/041/445/024/20210915103933/smaller_square/sebastian-cavazzoli-sebastian-cavazzoli-2cc.jpg?1631720373"
                        },
                        new
                        {
                            IdImage = new Guid("acc06c97-c77e-480c-9975-af2b69ae0d0c"),
                            ArtworkId = new Guid("5d2961ef-985f-44e4-93f0-5a563bb4ef62"),
                            CloudId = "",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Order = 2,
                            Src = "https://cdna.artstation.com/p/assets/images/images/041/444/824/large/sebastian-cavazzoli-2cc.jpg?1631719969"
                        },
                        new
                        {
                            IdImage = new Guid("44807e0b-28b7-460f-aa22-1fd9bccf6138"),
                            ArtworkId = new Guid("5d2961ef-985f-44e4-93f0-5a563bb4ef62"),
                            CloudId = "",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Order = 3,
                            Src = "https://cdnb.artstation.com/p/assets/images/images/041/444/801/large/sebastian-cavazzoli-1a.jpg?1631719947"
                        },
                        new
                        {
                            IdImage = new Guid("c424e740-d661-4e6a-ade6-ad8f0cdfed63"),
                            ArtworkId = new Guid("5d2961ef-985f-44e4-93f0-5a563bb4ef62"),
                            CloudId = "",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Order = 4,
                            Src = "https://cdnb.artstation.com/p/assets/images/images/041/444/927/large/sebastian-cavazzoli-2b.jpg?1631720155"
                        },
                        new
                        {
                            IdImage = new Guid("2c9f9c77-6127-4c52-9096-c253b8f3a4fc"),
                            ArtworkId = new Guid("5d2961ef-985f-44e4-93f0-5a563bb4ef62"),
                            CloudId = "",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Order = 5,
                            Src = "https://cdnb.artstation.com/p/assets/images/images/041/425/153/large/sebastian-cavazzoli-3b.jpg?1631660232"
                        },
                        new
                        {
                            IdImage = new Guid("bba17a7d-4a5b-4ec6-b7ff-60c175e92e5a"),
                            ArtworkId = new Guid("5d2961ef-985f-44e4-93f0-5a563bb4ef62"),
                            CloudId = "",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Order = 6,
                            Src = "https://cdnb.artstation.com/p/assets/images/images/041/444/995/large/sebastian-cavazzoli-1aa.jpg?1631720258"
                        },
                        new
                        {
                            IdImage = new Guid("bd53d473-79b7-4f2a-ac53-e784179a678f"),
                            ArtworkId = new Guid("5d2961ef-985f-44e4-93f0-5a563bb4ef62"),
                            CloudId = "",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Order = 7,
                            Src = "https://cdnb.artstation.com/p/assets/images/images/041/424/055/large/sebastian-cavazzoli-1e.jpg?1631656468"
                        },
                        new
                        {
                            IdImage = new Guid("f30079cd-ab98-4f45-bd43-cad54b79f316"),
                            ArtworkId = new Guid("5d2961ef-985f-44e4-93f0-5a563bb4ef62"),
                            CloudId = "",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Order = 8,
                            Src = "https://cdnb.artstation.com/p/assets/images/images/041/425/085/large/sebastian-cavazzoli-5.jpg?1631659895"
                        },
                        new
                        {
                            IdImage = new Guid("7f11f1cd-a506-4866-bb9e-078a9229a21b"),
                            ArtworkId = new Guid("5d2961ef-985f-44e4-93f0-5a563bb4ef62"),
                            CloudId = "",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Order = 9,
                            Src = "https://cdna.artstation.com/p/assets/images/images/041/444/934/large/sebastian-cavazzoli-bb.jpg?1631720169"
                        },
                        new
                        {
                            IdImage = new Guid("56ba2ceb-9600-4949-a366-43ef4ca8d9f6"),
                            ArtworkId = new Guid("24234d88-d57a-4a89-af74-999672025fc1"),
                            CloudId = "",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Order = 1,
                            Src = "https://cdnb.artstation.com/p/assets/covers/images/036/813/465/smaller_square/sebastian-cavazzoli-sebastian-cavazzoli-1.jpg?1618687643"
                        },
                        new
                        {
                            IdImage = new Guid("16fe6b23-d7ae-44d5-a783-3bbd12750c46"),
                            ArtworkId = new Guid("24234d88-d57a-4a89-af74-999672025fc1"),
                            CloudId = "",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Order = 2,
                            Src = "https://cdna.artstation.com/p/assets/images/images/036/813/236/large/sebastian-cavazzoli-2.jpg?1618687003"
                        },
                        new
                        {
                            IdImage = new Guid("b2c7375b-8b49-46e7-be9e-dcdb6bd11607"),
                            ArtworkId = new Guid("24234d88-d57a-4a89-af74-999672025fc1"),
                            CloudId = "",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Order = 3,
                            Src = "https://cdnb.artstation.com/p/assets/images/images/036/813/225/large/sebastian-cavazzoli-concept.jpg?1618686986"
                        },
                        new
                        {
                            IdImage = new Guid("58fddfa8-3fbc-40d2-bf76-e7c4467ecdd7"),
                            ArtworkId = new Guid("24234d88-d57a-4a89-af74-999672025fc1"),
                            CloudId = "",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Order = 4,
                            Src = "https://cdnb.artstation.com/p/assets/images/images/036/813/263/large/sebastian-cavazzoli-concept.jpg?1618687067"
                        },
                        new
                        {
                            IdImage = new Guid("e1520d82-80e3-4bb0-acd6-00485e344afa"),
                            ArtworkId = new Guid("24234d88-d57a-4a89-af74-999672025fc1"),
                            CloudId = "",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Order = 5,
                            Src = "https://cdnb.artstation.com/p/assets/images/images/036/813/269/large/sebastian-cavazzoli-1.jpg?1618687081"
                        },
                        new
                        {
                            IdImage = new Guid("30841827-fcec-4107-a506-f6a76833c28e"),
                            ArtworkId = new Guid("24234d88-d57a-4a89-af74-999672025fc1"),
                            CloudId = "",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Order = 6,
                            Src = "https://cdna.artstation.com/p/assets/images/images/036/813/276/large/sebastian-cavazzoli-2.jpg?1618687091"
                        },
                        new
                        {
                            IdImage = new Guid("44fd6cbe-757e-4687-90b0-406556fd6141"),
                            ArtworkId = new Guid("c809a906-01f9-4eee-bd68-1a7e46e97b21"),
                            CloudId = "",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Order = 1,
                            Src = "https://cdnb.artstation.com/p/assets/covers/images/034/485/459/20210203223805/smaller_square/sebastian-cavazzoli-sebastian-cavazzoli-01.jpg?1612413485"
                        },
                        new
                        {
                            IdImage = new Guid("a7398954-1770-4780-9653-4ac07c82bd18"),
                            ArtworkId = new Guid("c809a906-01f9-4eee-bd68-1a7e46e97b21"),
                            CloudId = "",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Order = 2,
                            Src = "https://cdnb.artstation.com/p/assets/images/images/034/483/381/large/sebastian-cavazzoli-01.jpg?1612404174"
                        },
                        new
                        {
                            IdImage = new Guid("152d78d8-134b-40ed-9c3a-ef4ca990dc1b"),
                            ArtworkId = new Guid("c809a906-01f9-4eee-bd68-1a7e46e97b21"),
                            CloudId = "",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Order = 3,
                            Src = "https://cdnb.artstation.com/p/assets/images/images/034/483/403/large/sebastian-cavazzoli-05.jpg?1612404233"
                        },
                        new
                        {
                            IdImage = new Guid("9af2563d-9916-488a-a4ea-0fd4755f7550"),
                            ArtworkId = new Guid("c809a906-01f9-4eee-bd68-1a7e46e97b21"),
                            CloudId = "",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Order = 4,
                            Src = "https://cdnb.artstation.com/p/assets/images/images/034/483/385/large/sebastian-cavazzoli-02.jpg?1612404193"
                        },
                        new
                        {
                            IdImage = new Guid("e693da76-a51a-4408-8fb6-55ae94776e80"),
                            ArtworkId = new Guid("c809a906-01f9-4eee-bd68-1a7e46e97b21"),
                            CloudId = "",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Order = 5,
                            Src = "https://cdnb.artstation.com/p/assets/images/images/034/483/389/large/sebastian-cavazzoli-03.jpg?1612404201"
                        });
                });

            modelBuilder.Entity("ArtLite.Api.Tag", b =>
                {
                    b.Property<Guid>("IdTag")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IdTag");

                    b.HasIndex("TagName")
                        .IsUnique();

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            IdTag = new Guid("0839b3dc-e20e-40dc-9fe1-c6525d54f461"),
                            TagName = "Digital 2D"
                        },
                        new
                        {
                            IdTag = new Guid("b50b6375-ecf3-4c86-97a4-9eeb1750d3c1"),
                            TagName = "Fantasy"
                        },
                        new
                        {
                            IdTag = new Guid("24595347-6c76-43b3-97f7-9fe2a6da2a1f"),
                            TagName = "Concept Art"
                        },
                        new
                        {
                            IdTag = new Guid("8ba9a6e8-84be-4ef0-acfc-b22d8a73b963"),
                            TagName = "Storytelling"
                        },
                        new
                        {
                            IdTag = new Guid("5b9379ba-5aee-4929-b0bd-b3b7ca0b27e0"),
                            TagName = "Character Design"
                        },
                        new
                        {
                            IdTag = new Guid("1d9ca9a0-09ef-4c8f-9b6f-08dc2823b535"),
                            TagName = "Sci-Fi"
                        },
                        new
                        {
                            IdTag = new Guid("616467f5-b3bb-4bbd-aaf9-04203410cf2b"),
                            TagName = "Abstract"
                        },
                        new
                        {
                            IdTag = new Guid("02e52d9d-fa79-46dc-9485-4ddb714d47e4"),
                            TagName = "Nature"
                        },
                        new
                        {
                            IdTag = new Guid("1661b07d-ca10-4cae-9cf0-62d98e226bad"),
                            TagName = "Portrait"
                        },
                        new
                        {
                            IdTag = new Guid("eb72089e-33fa-42d8-80fb-43be40f4f6fd"),
                            TagName = "Typography"
                        },
                        new
                        {
                            IdTag = new Guid("13550df2-3fe0-48ba-a978-e76fed9446d3"),
                            TagName = "Animation"
                        },
                        new
                        {
                            IdTag = new Guid("4b2e33cc-a082-48bc-be42-3e12de8592b1"),
                            TagName = "Minimalism"
                        },
                        new
                        {
                            IdTag = new Guid("479136d1-6434-4d4a-af2c-e5bcd2cf97e8"),
                            TagName = "Surrealism"
                        },
                        new
                        {
                            IdTag = new Guid("95150a51-6a05-48ac-a394-036436ef7f51"),
                            TagName = "Comics"
                        },
                        new
                        {
                            IdTag = new Guid("c5fb02bd-bf50-4463-b682-a220feb3e6fe"),
                            TagName = "Abstract Expressionism"
                        },
                        new
                        {
                            IdTag = new Guid("c29f0adf-f3d1-4baf-b21d-8f50db2611a6"),
                            TagName = "Photorealism"
                        },
                        new
                        {
                            IdTag = new Guid("5b3ddd89-1a19-43a8-8db6-12c354b49c83"),
                            TagName = "Urban Art"
                        },
                        new
                        {
                            IdTag = new Guid("5f6f013c-4e9e-432e-8cb3-e986af591aeb"),
                            TagName = "Graffiti"
                        },
                        new
                        {
                            IdTag = new Guid("a0cd7970-46fe-4399-8029-67913788fb60"),
                            TagName = "Calligraphy"
                        },
                        new
                        {
                            IdTag = new Guid("861a2ed1-a9a1-420b-8607-a312cfc8a494"),
                            TagName = "Cubism"
                        },
                        new
                        {
                            IdTag = new Guid("ef0aed54-124e-47f8-91a6-dec8cb654e1a"),
                            TagName = "Digital Painting"
                        },
                        new
                        {
                            IdTag = new Guid("3ba3eba1-770b-4ad4-b159-98fc4fd9c650"),
                            TagName = "Street Art"
                        },
                        new
                        {
                            IdTag = new Guid("cf0e2e7b-b321-4788-9c62-288cf1d643b6"),
                            TagName = "Impressionism"
                        },
                        new
                        {
                            IdTag = new Guid("a87b31a6-059c-4271-84dd-784c5b8e4f47"),
                            TagName = "Watercolor"
                        },
                        new
                        {
                            IdTag = new Guid("33156ba9-d1eb-4550-83d3-e0646724620a"),
                            TagName = "Pixel Art"
                        });
                });

            modelBuilder.Entity("ArtworkTag", b =>
                {
                    b.Property<Guid>("TagId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ArtworkId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TagId", "ArtworkId");

                    b.HasIndex("ArtworkId");

                    b.ToTable("ArtworkTag");

                    b.HasData(
                        new
                        {
                            TagId = new Guid("24595347-6c76-43b3-97f7-9fe2a6da2a1f"),
                            ArtworkId = new Guid("5d2961ef-985f-44e4-93f0-5a563bb4ef62")
                        },
                        new
                        {
                            TagId = new Guid("5b3ddd89-1a19-43a8-8db6-12c354b49c83"),
                            ArtworkId = new Guid("55b6cc08-d79d-4485-81c6-07ed39c064e5")
                        },
                        new
                        {
                            TagId = new Guid("5f6f013c-4e9e-432e-8cb3-e986af591aeb"),
                            ArtworkId = new Guid("1cd4cc4a-4a4a-4eb8-92b7-036a4e3d5520")
                        },
                        new
                        {
                            TagId = new Guid("5b3ddd89-1a19-43a8-8db6-12c354b49c83"),
                            ArtworkId = new Guid("7443d740-b827-47dd-9d92-0dff40042228")
                        },
                        new
                        {
                            TagId = new Guid("ef0aed54-124e-47f8-91a6-dec8cb654e1a"),
                            ArtworkId = new Guid("ca8d3891-f868-4da0-8774-29b259eb5c8f")
                        },
                        new
                        {
                            TagId = new Guid("b50b6375-ecf3-4c86-97a4-9eeb1750d3c1"),
                            ArtworkId = new Guid("5d2961ef-985f-44e4-93f0-5a563bb4ef62")
                        },
                        new
                        {
                            TagId = new Guid("24595347-6c76-43b3-97f7-9fe2a6da2a1f"),
                            ArtworkId = new Guid("5da4c9ae-86df-4632-8ffa-865d7a20b425")
                        },
                        new
                        {
                            TagId = new Guid("ef0aed54-124e-47f8-91a6-dec8cb654e1a"),
                            ArtworkId = new Guid("c25e263a-1ac6-4f26-867a-43deaa3f8f26")
                        },
                        new
                        {
                            TagId = new Guid("1661b07d-ca10-4cae-9cf0-62d98e226bad"),
                            ArtworkId = new Guid("edb8d3de-3a0e-4149-ad04-7b82c14eca57")
                        },
                        new
                        {
                            TagId = new Guid("eb72089e-33fa-42d8-80fb-43be40f4f6fd"),
                            ArtworkId = new Guid("55b6cc08-d79d-4485-81c6-07ed39c064e5")
                        },
                        new
                        {
                            TagId = new Guid("33156ba9-d1eb-4550-83d3-e0646724620a"),
                            ArtworkId = new Guid("edb8d3de-3a0e-4149-ad04-7b82c14eca57")
                        },
                        new
                        {
                            TagId = new Guid("1661b07d-ca10-4cae-9cf0-62d98e226bad"),
                            ArtworkId = new Guid("c809a906-01f9-4eee-bd68-1a7e46e97b21")
                        },
                        new
                        {
                            TagId = new Guid("5b3ddd89-1a19-43a8-8db6-12c354b49c83"),
                            ArtworkId = new Guid("932a65c4-ee3f-4b71-96ec-4b132b7c505e")
                        },
                        new
                        {
                            TagId = new Guid("eb72089e-33fa-42d8-80fb-43be40f4f6fd"),
                            ArtworkId = new Guid("edb8d3de-3a0e-4149-ad04-7b82c14eca57")
                        },
                        new
                        {
                            TagId = new Guid("eb72089e-33fa-42d8-80fb-43be40f4f6fd"),
                            ArtworkId = new Guid("c25e263a-1ac6-4f26-867a-43deaa3f8f26")
                        },
                        new
                        {
                            TagId = new Guid("c29f0adf-f3d1-4baf-b21d-8f50db2611a6"),
                            ArtworkId = new Guid("c809a906-01f9-4eee-bd68-1a7e46e97b21")
                        },
                        new
                        {
                            TagId = new Guid("3ba3eba1-770b-4ad4-b159-98fc4fd9c650"),
                            ArtworkId = new Guid("932a65c4-ee3f-4b71-96ec-4b132b7c505e")
                        },
                        new
                        {
                            TagId = new Guid("13550df2-3fe0-48ba-a978-e76fed9446d3"),
                            ArtworkId = new Guid("7443d740-b827-47dd-9d92-0dff40042228")
                        },
                        new
                        {
                            TagId = new Guid("95150a51-6a05-48ac-a394-036436ef7f51"),
                            ArtworkId = new Guid("1cd4cc4a-4a4a-4eb8-92b7-036a4e3d5520")
                        },
                        new
                        {
                            TagId = new Guid("95150a51-6a05-48ac-a394-036436ef7f51"),
                            ArtworkId = new Guid("5d2961ef-985f-44e4-93f0-5a563bb4ef62")
                        },
                        new
                        {
                            TagId = new Guid("eb72089e-33fa-42d8-80fb-43be40f4f6fd"),
                            ArtworkId = new Guid("7443d740-b827-47dd-9d92-0dff40042228")
                        },
                        new
                        {
                            TagId = new Guid("5b9379ba-5aee-4929-b0bd-b3b7ca0b27e0"),
                            ArtworkId = new Guid("6d4facd0-299c-4d96-835e-b3fad8986c5a")
                        },
                        new
                        {
                            TagId = new Guid("616467f5-b3bb-4bbd-aaf9-04203410cf2b"),
                            ArtworkId = new Guid("55b6cc08-d79d-4485-81c6-07ed39c064e5")
                        },
                        new
                        {
                            TagId = new Guid("1661b07d-ca10-4cae-9cf0-62d98e226bad"),
                            ArtworkId = new Guid("6d4facd0-299c-4d96-835e-b3fad8986c5a")
                        },
                        new
                        {
                            TagId = new Guid("479136d1-6434-4d4a-af2c-e5bcd2cf97e8"),
                            ArtworkId = new Guid("932a65c4-ee3f-4b71-96ec-4b132b7c505e")
                        },
                        new
                        {
                            TagId = new Guid("b50b6375-ecf3-4c86-97a4-9eeb1750d3c1"),
                            ArtworkId = new Guid("edb8d3de-3a0e-4149-ad04-7b82c14eca57")
                        },
                        new
                        {
                            TagId = new Guid("616467f5-b3bb-4bbd-aaf9-04203410cf2b"),
                            ArtworkId = new Guid("05e8dad6-4683-4e79-acdc-bceada8b55a6")
                        },
                        new
                        {
                            TagId = new Guid("b50b6375-ecf3-4c86-97a4-9eeb1750d3c1"),
                            ArtworkId = new Guid("05e8dad6-4683-4e79-acdc-bceada8b55a6")
                        },
                        new
                        {
                            TagId = new Guid("a0cd7970-46fe-4399-8029-67913788fb60"),
                            ArtworkId = new Guid("55b6cc08-d79d-4485-81c6-07ed39c064e5")
                        },
                        new
                        {
                            TagId = new Guid("a87b31a6-059c-4271-84dd-784c5b8e4f47"),
                            ArtworkId = new Guid("c809a906-01f9-4eee-bd68-1a7e46e97b21")
                        },
                        new
                        {
                            TagId = new Guid("ef0aed54-124e-47f8-91a6-dec8cb654e1a"),
                            ArtworkId = new Guid("55b6cc08-d79d-4485-81c6-07ed39c064e5")
                        },
                        new
                        {
                            TagId = new Guid("c5fb02bd-bf50-4463-b682-a220feb3e6fe"),
                            ArtworkId = new Guid("7443d740-b827-47dd-9d92-0dff40042228")
                        },
                        new
                        {
                            TagId = new Guid("3ba3eba1-770b-4ad4-b159-98fc4fd9c650"),
                            ArtworkId = new Guid("24234d88-d57a-4a89-af74-999672025fc1")
                        },
                        new
                        {
                            TagId = new Guid("4b2e33cc-a082-48bc-be42-3e12de8592b1"),
                            ArtworkId = new Guid("ca8d3891-f868-4da0-8774-29b259eb5c8f")
                        },
                        new
                        {
                            TagId = new Guid("95150a51-6a05-48ac-a394-036436ef7f51"),
                            ArtworkId = new Guid("932a65c4-ee3f-4b71-96ec-4b132b7c505e")
                        },
                        new
                        {
                            TagId = new Guid("1661b07d-ca10-4cae-9cf0-62d98e226bad"),
                            ArtworkId = new Guid("7443d740-b827-47dd-9d92-0dff40042228")
                        },
                        new
                        {
                            TagId = new Guid("1661b07d-ca10-4cae-9cf0-62d98e226bad"),
                            ArtworkId = new Guid("55b6cc08-d79d-4485-81c6-07ed39c064e5")
                        },
                        new
                        {
                            TagId = new Guid("8ba9a6e8-84be-4ef0-acfc-b22d8a73b963"),
                            ArtworkId = new Guid("bb6aace8-b87f-4789-9f87-9f61da57ae72")
                        },
                        new
                        {
                            TagId = new Guid("cf0e2e7b-b321-4788-9c62-288cf1d643b6"),
                            ArtworkId = new Guid("932a65c4-ee3f-4b71-96ec-4b132b7c505e")
                        },
                        new
                        {
                            TagId = new Guid("eb72089e-33fa-42d8-80fb-43be40f4f6fd"),
                            ArtworkId = new Guid("1cd4cc4a-4a4a-4eb8-92b7-036a4e3d5520")
                        },
                        new
                        {
                            TagId = new Guid("5b9379ba-5aee-4929-b0bd-b3b7ca0b27e0"),
                            ArtworkId = new Guid("edb8d3de-3a0e-4149-ad04-7b82c14eca57")
                        });
                });

            modelBuilder.Entity("ArtLite.Api.Entities.Artwork", b =>
                {
                    b.HasOne("ArtLite.Api.Entities.Creator", "Creator")
                        .WithMany("Artworks")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("ArtLite.Api.Entities.Image", b =>
                {
                    b.HasOne("ArtLite.Api.Entities.Artwork", "Artwork")
                        .WithMany("Images")
                        .HasForeignKey("ArtworkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artwork");
                });

            modelBuilder.Entity("ArtworkTag", b =>
                {
                    b.HasOne("ArtLite.Api.Entities.Artwork", null)
                        .WithMany()
                        .HasForeignKey("ArtworkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArtLite.Api.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ArtLite.Api.Entities.Artwork", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("ArtLite.Api.Entities.Creator", b =>
                {
                    b.Navigation("Artworks");
                });
#pragma warning restore 612, 618
        }
    }
}
