// <auto-generated />
using System;
using ArtLite.Api.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ArtLite.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ArtLite.Api.Entities.Artwork", b =>
                {
                    b.Property<Guid>("IdArtwork")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("IdArtwork");

                    b.HasIndex("CreatorId");

                    b.ToTable("Artworks");

                    b.HasData(
                        new
                        {
                            IdArtwork = new Guid("f6b41168-339d-43be-bb15-0ac734e9beb6"),
                            CreatedAt = new DateTime(2023, 10, 19, 20, 8, 29, 875, DateTimeKind.Local).AddTicks(9593),
                            CreatorId = new Guid("28f9b607-474f-403f-9f17-34a6fc6676c1"),
                            Description = "Iusto quia inventore voluptas expedita laborum eum omnis occaecati. Qui nihil aperiam assumenda eveniet autem. Vel sit libero rerum animi.",
                            Title = "Repellendus id minus eum rerum et magni.",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            IdArtwork = new Guid("ad8562fd-0417-4815-ac85-d0fb26df0f59"),
                            CreatedAt = new DateTime(2023, 8, 2, 3, 44, 37, 523, DateTimeKind.Local).AddTicks(6950),
                            CreatorId = new Guid("28f9b607-474f-403f-9f17-34a6fc6676c1"),
                            Description = "Possimus facilis quia sed ipsum officiis qui qui molestias. Doloremque ea id voluptates facere fugiat fugiat. Rerum atque quibusdam. Non fugiat voluptatem qui nisi sunt. Qui rerum rerum praesentium molestiae hic iure. Ea quia et iste excepturi nesciunt.",
                            Title = "Et vitae aut et officiis harum.",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            IdArtwork = new Guid("d500f602-37bf-4de8-a1f8-62086c522dde"),
                            CreatedAt = new DateTime(2023, 2, 28, 13, 47, 12, 657, DateTimeKind.Local).AddTicks(3395),
                            CreatorId = new Guid("28f9b607-474f-403f-9f17-34a6fc6676c1"),
                            Description = "Consequatur sit quo quos sint officia. Dolore eius consequatur harum ratione earum consequatur. Commodi iure voluptatum et quia molestiae quis ut natus voluptatem. Pariatur facere et nihil id. Saepe sit et. Tempore a nulla et eveniet enim exercitationem.",
                            Title = "Placeat id officia voluptas dolor voluptate accusamus.",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            IdArtwork = new Guid("4df9a024-1d3d-4002-bb8e-f4f5d7ac94c9"),
                            CreatedAt = new DateTime(2023, 1, 25, 15, 52, 51, 876, DateTimeKind.Local).AddTicks(1045),
                            CreatorId = new Guid("28f9b607-474f-403f-9f17-34a6fc6676c1"),
                            Description = "Quisquam veritatis sequi tempora et quod dolor. Quibusdam harum laborum. Molestiae necessitatibus nisi est molestiae. Sit enim et asperiores voluptatum dolorem voluptas laudantium. Quia minima et et hic aut et sed omnis occaecati. Animi officiis sed corporis dolores nesciunt quia quia.",
                            Title = "Nihil consequatur molestiae et delectus autem recusandae et.",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            IdArtwork = new Guid("30554c9d-9e81-4c3f-8a51-a39cacdf4089"),
                            CreatedAt = new DateTime(2023, 12, 13, 4, 17, 38, 633, DateTimeKind.Local).AddTicks(703),
                            CreatorId = new Guid("28f9b607-474f-403f-9f17-34a6fc6676c1"),
                            Description = "Rem eveniet est officia voluptas eum omnis illum expedita est. Eum nam eos nihil. Autem dolorem optio accusantium nemo consectetur enim dolores. Cumque libero culpa rerum voluptas.",
                            Title = "Veniam ad commodi.",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            IdArtwork = new Guid("a4d2f0ca-e445-46ac-831e-8c384380f9cc"),
                            CreatedAt = new DateTime(2022, 12, 24, 5, 9, 36, 524, DateTimeKind.Local).AddTicks(5734),
                            CreatorId = new Guid("28f9b607-474f-403f-9f17-34a6fc6676c1"),
                            Description = "Ut dolorem illo laudantium. Sit sit praesentium aperiam praesentium ut quos. Nam ad in. Qui incidunt ut fuga porro. Non vel quisquam ut. Animi et qui non eum.",
                            Title = "Et et quidem animi voluptatum.",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            IdArtwork = new Guid("e6d916b8-4b51-4ab3-b515-1a3b7ba7c1a1"),
                            CreatedAt = new DateTime(2023, 11, 13, 0, 4, 32, 383, DateTimeKind.Local).AddTicks(9545),
                            CreatorId = new Guid("28f9b607-474f-403f-9f17-34a6fc6676c1"),
                            Description = "Harum sed ut aliquid. Mollitia tempora quos ex perferendis et optio similique et fuga. Est vero molestiae. Eos provident rerum. Nam eos ipsam quasi. Omnis at et veniam eum.",
                            Title = "Sed aliquam qui minus neque.",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            IdArtwork = new Guid("2e26f14e-fd5b-4814-8fb2-09777b0aab55"),
                            CreatedAt = new DateTime(2023, 5, 28, 11, 18, 29, 305, DateTimeKind.Local).AddTicks(9927),
                            CreatorId = new Guid("28f9b607-474f-403f-9f17-34a6fc6676c1"),
                            Description = "Odit ratione aut. Magni ea quisquam culpa magni vitae officiis id maiores vel. Deleniti voluptate nobis. Veniam sequi dolorem et neque quia esse sit perspiciatis.",
                            Title = "Reprehenderit laudantium eum.",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            IdArtwork = new Guid("26257a46-de7c-407f-ab81-48b6b9f3c38c"),
                            CreatedAt = new DateTime(2023, 1, 1, 9, 5, 47, 585, DateTimeKind.Local).AddTicks(9332),
                            CreatorId = new Guid("28f9b607-474f-403f-9f17-34a6fc6676c1"),
                            Description = "Deserunt quos adipisci rem voluptatibus sit exercitationem consequatur. Mollitia maiores omnis quasi voluptatem hic earum nisi facilis autem. Eius dolor doloremque qui eveniet nulla et dicta. Impedit est et sequi accusantium est nam aut. Sit nulla sed dolor iste.",
                            Title = "Sit doloremque quia eveniet facere iure fugiat neque.",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            IdArtwork = new Guid("f7140316-7c2a-4876-b479-f2cbcafa8b61"),
                            CreatedAt = new DateTime(2023, 2, 24, 4, 37, 9, 690, DateTimeKind.Local).AddTicks(1494),
                            CreatorId = new Guid("28f9b607-474f-403f-9f17-34a6fc6676c1"),
                            Description = "Esse praesentium quibusdam sunt dolores quo non. Ad hic maxime fuga quae suscipit. Delectus perferendis praesentium hic mollitia. Dolorum vitae est. Rerum sint dolores vel libero blanditiis. Suscipit excepturi enim sed dolor possimus quae magni voluptates.",
                            Title = "Ea a aspernatur hic vel ipsa consectetur consequatur.",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            IdArtwork = new Guid("150d08d9-bdb5-478f-a6a2-88b207fc8cd5"),
                            CreatedAt = new DateTime(2023, 12, 3, 15, 8, 11, 737, DateTimeKind.Local).AddTicks(5226),
                            CreatorId = new Guid("28f9b607-474f-403f-9f17-34a6fc6676c1"),
                            Description = "Doloremque qui quam modi rem quibusdam vel ratione beatae. Velit architecto natus est quos. Nostrum sed veritatis vitae temporibus aliquam esse qui est. Laboriosam vitae facilis porro. Facere rem ut quidem est blanditiis fugit ipsa rem dolorem.",
                            Title = "Alias alias omnis voluptates voluptas.",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            IdArtwork = new Guid("22f24ced-61c1-4125-b46d-43422f62e7bf"),
                            CreatedAt = new DateTime(2023, 5, 9, 16, 56, 50, 244, DateTimeKind.Local).AddTicks(5733),
                            CreatorId = new Guid("28f9b607-474f-403f-9f17-34a6fc6676c1"),
                            Description = "Culpa inventore omnis ipsam mollitia sed incidunt praesentium. Et commodi ad dignissimos id. Aut assumenda quam dolor quos officia quaerat. In dolorum necessitatibus at repellat libero sunt sint tempora.",
                            Title = "Autem recusandae fugiat labore tempore molestias magni corrupti.",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            IdArtwork = new Guid("8fd0689d-5fd4-47c6-bb4d-3d38b624b9f2"),
                            CreatedAt = new DateTime(2023, 5, 23, 14, 34, 45, 124, DateTimeKind.Local).AddTicks(7442),
                            CreatorId = new Guid("28f9b607-474f-403f-9f17-34a6fc6676c1"),
                            Description = "Culpa consequatur perferendis cupiditate non ipsam sint corrupti incidunt. Optio quod quo enim aut aut voluptatem ullam. Optio nihil soluta ut. Est maiores eos cum iure quo nobis fugit ea.",
                            Title = "Necessitatibus voluptates vero.",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            IdArtwork = new Guid("73bcb7ea-c460-48bd-8693-9551b27aef2d"),
                            CreatedAt = new DateTime(2023, 10, 23, 13, 0, 57, 213, DateTimeKind.Local).AddTicks(7874),
                            CreatorId = new Guid("28f9b607-474f-403f-9f17-34a6fc6676c1"),
                            Description = "Aut fugiat aut sint porro. Sunt laborum distinctio quo voluptatem eveniet sunt tempora et ut. Voluptas aspernatur occaecati sapiente. Eum voluptatem quo velit sed officia et. Deserunt nemo illo rerum illum necessitatibus sit eius sapiente ducimus.",
                            Title = "Nobis sunt minus incidunt voluptatem aut in.",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            IdArtwork = new Guid("e49edb7b-926c-4ae6-9dab-4c81bbaf2b23"),
                            CreatedAt = new DateTime(2023, 7, 30, 9, 37, 51, 191, DateTimeKind.Local).AddTicks(9832),
                            CreatorId = new Guid("28f9b607-474f-403f-9f17-34a6fc6676c1"),
                            Description = "Ut non eligendi. Voluptatem ullam odit. Reprehenderit qui et sed sint ea. Perspiciatis quisquam sed nulla voluptas est voluptate repudiandae ea a. Et autem necessitatibus quia id quod perferendis sunt consectetur expedita.",
                            Title = "Blanditiis facilis voluptate.",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("ArtLite.Api.Entities.Creator", b =>
                {
                    b.Property<Guid>("IdCreator")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Biography")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("HighlightedPhrase")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileBanner")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SocialFacebook")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SocialFigma")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SocialInstagram")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SocialLinkedin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SocialYoutube")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCreator");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Creators");

                    b.HasData(
                        new
                        {
                            IdCreator = new Guid("28f9b607-474f-403f-9f17-34a6fc6676c1"),
                            Biography = "3D Character Artist. I have a passion for 3D art. Currently working on my own personal projects!",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sebas@gmail.com",
                            HighlightedPhrase = "3D Character Artist",
                            ProfileBanner = "https://cdna.artstation.com/p/users/covers/000/583/624/default/73c0b86e24cfe09e6954896a1b24b5c0.jpg?1687826140",
                            ProfileImage = "https://cdna.artstation.com/p/users/avatars/000/583/624/large/21ab51c6fdec0656327acd1decc6b95f.jpg?1521491898",
                            Slug = "sebastian_cavazzoli",
                            SocialFacebook = "",
                            SocialFigma = "",
                            SocialInstagram = "https://www.instagram.com/sebacavazzoli.art",
                            SocialLinkedin = "",
                            SocialYoutube = "https://www.youtube.com/sebastiancavazzoli",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "Sebastian Cavazzoli"
                        });
                });

            modelBuilder.Entity("ArtLite.Api.Entities.Image", b =>
                {
                    b.Property<Guid>("IdImage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ArtworkId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CloudId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Src")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdImage");

                    b.HasIndex("ArtworkId");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            IdImage = new Guid("2067b823-8cee-42a7-bcbc-b6a28fc977e2"),
                            ArtworkId = new Guid("f6b41168-339d-43be-bb15-0ac734e9beb6"),
                            CloudId = "",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Order = 1,
                            Src = "https://cdnb.artstation.com/p/assets/images/images/070/397/485/20231212212844/smaller_square/sebastian-cavazzoli-2313313.jpg?1702438125"
                        },
                        new
                        {
                            IdImage = new Guid("590eb79b-b69e-488f-a7cb-c4b9ecf4e5a0"),
                            ArtworkId = new Guid("ad8562fd-0417-4815-ac85-d0fb26df0f59"),
                            CloudId = "",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Order = 1,
                            Src = "https://cdnb.artstation.com/p/assets/images/images/064/384/223/smaller_square/sebastian-cavazzoli-1.jpg?1687806929"
                        },
                        new
                        {
                            IdImage = new Guid("f76d742f-e590-4324-995a-a9f9e514e33b"),
                            ArtworkId = new Guid("d500f602-37bf-4de8-a1f8-62086c522dde"),
                            CloudId = "",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Order = 1,
                            Src = "https://cdnb.artstation.com/p/assets/video_clips/images/066/131/241/smaller_square/sebastian-cavazzoli-thumb.jpg?1692121620"
                        },
                        new
                        {
                            IdImage = new Guid("ae4e5710-595f-492f-af42-3b9243388c0a"),
                            ArtworkId = new Guid("4df9a024-1d3d-4002-bb8e-f4f5d7ac94c9"),
                            CloudId = "",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Order = 1,
                            Src = "https://cdnb.artstation.com/p/assets/images/images/062/527/639/smaller_square/sebastian-cavazzoli-04a4ddc0-1c5c-42a3-b4ff-5e8c77014ad4.jpg?1683333990"
                        },
                        new
                        {
                            IdImage = new Guid("d9068280-3ee9-470b-8486-c31a29027d21"),
                            ArtworkId = new Guid("30554c9d-9e81-4c3f-8a51-a39cacdf4089"),
                            CloudId = "",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Order = 1,
                            Src = "https://cdnb.artstation.com/p/assets/images/images/058/444/123/smaller_square/sebastian-cavazzoli-1b.jpg?1674161052"
                        },
                        new
                        {
                            IdImage = new Guid("ac6d86f4-f434-46ba-b930-4b8dfd65d70d"),
                            ArtworkId = new Guid("a4d2f0ca-e445-46ac-831e-8c384380f9cc"),
                            CloudId = "",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Order = 1,
                            Src = "https://cdnb.artstation.com/p/assets/images/images/055/727/009/smaller_square/sebastian-cavazzoli-1.jpg?1667597373"
                        },
                        new
                        {
                            IdImage = new Guid("25c09c68-4a4f-4c48-9539-7e1598ffa061"),
                            ArtworkId = new Guid("e6d916b8-4b51-4ab3-b515-1a3b7ba7c1a1"),
                            CloudId = "",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Order = 1,
                            Src = "https://cdnb.artstation.com/p/assets/covers/images/052/375/327/20220807090628/smaller_square/sebastian-cavazzoli-sebastian-cavazzoli-cheloportada2.jpg?1659881189"
                        },
                        new
                        {
                            IdImage = new Guid("a9e808ea-4e2c-460d-9740-cb04162189a6"),
                            ArtworkId = new Guid("2e26f14e-fd5b-4814-8fb2-09777b0aab55"),
                            CloudId = "",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Order = 1,
                            Src = "https://cdna.artstation.com/p/assets/video_clips/images/045/020/050/smaller_square/sebastian-cavazzoli-thumb.jpg?1641742817"
                        },
                        new
                        {
                            IdImage = new Guid("74f6aeb0-e140-4b7f-b915-ee9ef5f5ecb5"),
                            ArtworkId = new Guid("26257a46-de7c-407f-ab81-48b6b9f3c38c"),
                            CloudId = "",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Order = 1,
                            Src = "https://cdna.artstation.com/p/assets/covers/images/037/967/798/smaller_square/sebastian-cavazzoli-sebastian-cavazzoli-3.jpg?1621816194"
                        },
                        new
                        {
                            IdImage = new Guid("ee6f7bf2-dbb6-41da-beac-f531e2a98de1"),
                            ArtworkId = new Guid("f7140316-7c2a-4876-b479-f2cbcafa8b61"),
                            CloudId = "",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Order = 1,
                            Src = "https://cdna.artstation.com/p/assets/images/images/036/831/246/20210418093453/smaller_square/sebastian-cavazzoli-widefsnew.jpg?1618756493"
                        },
                        new
                        {
                            IdImage = new Guid("2803c917-5288-40db-a7b3-bcf5485a1503"),
                            ArtworkId = new Guid("150d08d9-bdb5-478f-a6a2-88b207fc8cd5"),
                            CloudId = "",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Order = 1,
                            Src = "https://cdnb.artstation.com/p/assets/images/images/038/143/017/smaller_square/sebastian-cavazzoli-7.jpg?1622294979"
                        },
                        new
                        {
                            IdImage = new Guid("30d3c417-35eb-437e-a63d-ea164f10e856"),
                            ArtworkId = new Guid("22f24ced-61c1-4125-b46d-43422f62e7bf"),
                            CloudId = "",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Order = 1,
                            Src = "https://cdnb.artstation.com/p/assets/images/images/070/397/631/smaller_square/sebastian-cavazzoli-close2.jpg?1702438582"
                        },
                        new
                        {
                            IdImage = new Guid("30f36dc7-2299-4762-b069-739546fbd913"),
                            ArtworkId = new Guid("8fd0689d-5fd4-47c6-bb4d-3d38b624b9f2"),
                            CloudId = "",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Order = 1,
                            Src = "https://cdna.artstation.com/p/assets/covers/images/041/445/024/20210915103933/smaller_square/sebastian-cavazzoli-sebastian-cavazzoli-2cc.jpg?1631720373"
                        },
                        new
                        {
                            IdImage = new Guid("91a4bacf-9c0d-4ca3-86e4-074222cf0465"),
                            ArtworkId = new Guid("73bcb7ea-c460-48bd-8693-9551b27aef2d"),
                            CloudId = "",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Order = 1,
                            Src = "https://cdnb.artstation.com/p/assets/covers/images/036/813/465/smaller_square/sebastian-cavazzoli-sebastian-cavazzoli-1.jpg?1618687643"
                        },
                        new
                        {
                            IdImage = new Guid("e9da5353-7cd2-4550-9f10-1fbf1c86f2ed"),
                            ArtworkId = new Guid("e49edb7b-926c-4ae6-9dab-4c81bbaf2b23"),
                            CloudId = "",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Order = 1,
                            Src = "https://cdnb.artstation.com/p/assets/covers/images/034/485/459/20210203223805/smaller_square/sebastian-cavazzoli-sebastian-cavazzoli-01.jpg?1612413485"
                        });
                });

            modelBuilder.Entity("ArtLite.Api.Tag", b =>
                {
                    b.Property<Guid>("IdTag")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTag");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            IdTag = new Guid("b6898f28-de2c-4198-9e4c-e857fbaf04a7"),
                            TagName = "Digital 2D"
                        },
                        new
                        {
                            IdTag = new Guid("b3b265b5-847f-4fc1-b343-4c601d941a06"),
                            TagName = "Fantasy"
                        },
                        new
                        {
                            IdTag = new Guid("ccc175b1-c0ba-438f-9ff5-6628bece730c"),
                            TagName = "Concept Art"
                        },
                        new
                        {
                            IdTag = new Guid("e7ffe31c-a60c-47a4-9c7c-14197683e390"),
                            TagName = "Storytelling"
                        },
                        new
                        {
                            IdTag = new Guid("8f47c5c7-1d60-43bd-b910-08c941ca1a43"),
                            TagName = "Character Design"
                        },
                        new
                        {
                            IdTag = new Guid("2a2a8a52-b096-4788-a9f1-604bab8e2eec"),
                            TagName = "Sci-Fi"
                        },
                        new
                        {
                            IdTag = new Guid("7af38711-1dff-449e-b400-3b3c1e0c5ce6"),
                            TagName = "Abstract"
                        },
                        new
                        {
                            IdTag = new Guid("a9f7f755-e1c5-4c1c-946c-e8878a4ad43e"),
                            TagName = "Nature"
                        },
                        new
                        {
                            IdTag = new Guid("c1a513ee-7361-41f8-b1fb-5d22ae60511e"),
                            TagName = "Portrait"
                        },
                        new
                        {
                            IdTag = new Guid("1bb27278-c3c0-4910-be37-2c978aa0e597"),
                            TagName = "Typography"
                        },
                        new
                        {
                            IdTag = new Guid("d2893a9c-95d6-49c8-b669-d6743d955657"),
                            TagName = "Animation"
                        },
                        new
                        {
                            IdTag = new Guid("b0a7936a-4c23-4213-ad3c-5f53745197e7"),
                            TagName = "Minimalism"
                        },
                        new
                        {
                            IdTag = new Guid("c6d15992-5875-4c1a-802e-c9c254963ace"),
                            TagName = "Surrealism"
                        },
                        new
                        {
                            IdTag = new Guid("bb5447bc-5b00-4a73-89ce-6c81aa518b4a"),
                            TagName = "Comics"
                        },
                        new
                        {
                            IdTag = new Guid("99b58f35-c024-4ca5-9247-318d36335abf"),
                            TagName = "Abstract Expressionism"
                        },
                        new
                        {
                            IdTag = new Guid("5d458006-6af0-4293-afc8-388805314e79"),
                            TagName = "Photorealism"
                        },
                        new
                        {
                            IdTag = new Guid("0f4a3ee3-8006-43ff-9f14-450e83352ce2"),
                            TagName = "Urban Art"
                        },
                        new
                        {
                            IdTag = new Guid("8914de02-37bb-4df9-8d3c-fc652ee654c0"),
                            TagName = "Graffiti"
                        },
                        new
                        {
                            IdTag = new Guid("278bf2f7-8ea4-49d6-89af-57cdba17ea52"),
                            TagName = "Calligraphy"
                        },
                        new
                        {
                            IdTag = new Guid("91e97a37-d394-46c1-9056-3cced711ef97"),
                            TagName = "Cubism"
                        },
                        new
                        {
                            IdTag = new Guid("09b9b49d-8bba-4945-8de4-e2a56feabb22"),
                            TagName = "Digital Painting"
                        },
                        new
                        {
                            IdTag = new Guid("72db3ce9-f1ff-465f-9cef-78d496f4160d"),
                            TagName = "Street Art"
                        },
                        new
                        {
                            IdTag = new Guid("f3b21212-2734-409f-a7b3-d20aff4a8857"),
                            TagName = "Impressionism"
                        },
                        new
                        {
                            IdTag = new Guid("e8214540-73f3-4225-bf88-45eabab70edc"),
                            TagName = "Watercolor"
                        },
                        new
                        {
                            IdTag = new Guid("b2b9220f-949f-4379-9b2c-d259215e7b20"),
                            TagName = "Pixel Art"
                        });
                });

            modelBuilder.Entity("ArtworkTag", b =>
                {
                    b.Property<Guid>("TagId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ArtworkId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TagId", "ArtworkId");

                    b.HasIndex("ArtworkId");

                    b.ToTable("ArtworkTag");

                    b.HasData(
                        new
                        {
                            TagId = new Guid("b0a7936a-4c23-4213-ad3c-5f53745197e7"),
                            ArtworkId = new Guid("30554c9d-9e81-4c3f-8a51-a39cacdf4089")
                        },
                        new
                        {
                            TagId = new Guid("0f4a3ee3-8006-43ff-9f14-450e83352ce2"),
                            ArtworkId = new Guid("f7140316-7c2a-4876-b479-f2cbcafa8b61")
                        },
                        new
                        {
                            TagId = new Guid("72db3ce9-f1ff-465f-9cef-78d496f4160d"),
                            ArtworkId = new Guid("4df9a024-1d3d-4002-bb8e-f4f5d7ac94c9")
                        },
                        new
                        {
                            TagId = new Guid("0f4a3ee3-8006-43ff-9f14-450e83352ce2"),
                            ArtworkId = new Guid("4df9a024-1d3d-4002-bb8e-f4f5d7ac94c9")
                        },
                        new
                        {
                            TagId = new Guid("0f4a3ee3-8006-43ff-9f14-450e83352ce2"),
                            ArtworkId = new Guid("8fd0689d-5fd4-47c6-bb4d-3d38b624b9f2")
                        },
                        new
                        {
                            TagId = new Guid("278bf2f7-8ea4-49d6-89af-57cdba17ea52"),
                            ArtworkId = new Guid("a4d2f0ca-e445-46ac-831e-8c384380f9cc")
                        },
                        new
                        {
                            TagId = new Guid("5d458006-6af0-4293-afc8-388805314e79"),
                            ArtworkId = new Guid("73bcb7ea-c460-48bd-8693-9551b27aef2d")
                        },
                        new
                        {
                            TagId = new Guid("b6898f28-de2c-4198-9e4c-e857fbaf04a7"),
                            ArtworkId = new Guid("150d08d9-bdb5-478f-a6a2-88b207fc8cd5")
                        },
                        new
                        {
                            TagId = new Guid("f3b21212-2734-409f-a7b3-d20aff4a8857"),
                            ArtworkId = new Guid("30554c9d-9e81-4c3f-8a51-a39cacdf4089")
                        },
                        new
                        {
                            TagId = new Guid("b3b265b5-847f-4fc1-b343-4c601d941a06"),
                            ArtworkId = new Guid("f6b41168-339d-43be-bb15-0ac734e9beb6")
                        },
                        new
                        {
                            TagId = new Guid("2a2a8a52-b096-4788-a9f1-604bab8e2eec"),
                            ArtworkId = new Guid("f6b41168-339d-43be-bb15-0ac734e9beb6")
                        },
                        new
                        {
                            TagId = new Guid("7af38711-1dff-449e-b400-3b3c1e0c5ce6"),
                            ArtworkId = new Guid("f7140316-7c2a-4876-b479-f2cbcafa8b61")
                        },
                        new
                        {
                            TagId = new Guid("7af38711-1dff-449e-b400-3b3c1e0c5ce6"),
                            ArtworkId = new Guid("e49edb7b-926c-4ae6-9dab-4c81bbaf2b23")
                        },
                        new
                        {
                            TagId = new Guid("7af38711-1dff-449e-b400-3b3c1e0c5ce6"),
                            ArtworkId = new Guid("4df9a024-1d3d-4002-bb8e-f4f5d7ac94c9")
                        },
                        new
                        {
                            TagId = new Guid("5d458006-6af0-4293-afc8-388805314e79"),
                            ArtworkId = new Guid("150d08d9-bdb5-478f-a6a2-88b207fc8cd5")
                        },
                        new
                        {
                            TagId = new Guid("e7ffe31c-a60c-47a4-9c7c-14197683e390"),
                            ArtworkId = new Guid("e49edb7b-926c-4ae6-9dab-4c81bbaf2b23")
                        },
                        new
                        {
                            TagId = new Guid("c6d15992-5875-4c1a-802e-c9c254963ace"),
                            ArtworkId = new Guid("f7140316-7c2a-4876-b479-f2cbcafa8b61")
                        },
                        new
                        {
                            TagId = new Guid("278bf2f7-8ea4-49d6-89af-57cdba17ea52"),
                            ArtworkId = new Guid("f6b41168-339d-43be-bb15-0ac734e9beb6")
                        },
                        new
                        {
                            TagId = new Guid("72db3ce9-f1ff-465f-9cef-78d496f4160d"),
                            ArtworkId = new Guid("8fd0689d-5fd4-47c6-bb4d-3d38b624b9f2")
                        },
                        new
                        {
                            TagId = new Guid("72db3ce9-f1ff-465f-9cef-78d496f4160d"),
                            ArtworkId = new Guid("ad8562fd-0417-4815-ac85-d0fb26df0f59")
                        },
                        new
                        {
                            TagId = new Guid("b2b9220f-949f-4379-9b2c-d259215e7b20"),
                            ArtworkId = new Guid("f7140316-7c2a-4876-b479-f2cbcafa8b61")
                        },
                        new
                        {
                            TagId = new Guid("72db3ce9-f1ff-465f-9cef-78d496f4160d"),
                            ArtworkId = new Guid("2e26f14e-fd5b-4814-8fb2-09777b0aab55")
                        },
                        new
                        {
                            TagId = new Guid("91e97a37-d394-46c1-9056-3cced711ef97"),
                            ArtworkId = new Guid("2e26f14e-fd5b-4814-8fb2-09777b0aab55")
                        },
                        new
                        {
                            TagId = new Guid("1bb27278-c3c0-4910-be37-2c978aa0e597"),
                            ArtworkId = new Guid("a4d2f0ca-e445-46ac-831e-8c384380f9cc")
                        },
                        new
                        {
                            TagId = new Guid("b2b9220f-949f-4379-9b2c-d259215e7b20"),
                            ArtworkId = new Guid("30554c9d-9e81-4c3f-8a51-a39cacdf4089")
                        },
                        new
                        {
                            TagId = new Guid("c1a513ee-7361-41f8-b1fb-5d22ae60511e"),
                            ArtworkId = new Guid("30554c9d-9e81-4c3f-8a51-a39cacdf4089")
                        },
                        new
                        {
                            TagId = new Guid("e7ffe31c-a60c-47a4-9c7c-14197683e390"),
                            ArtworkId = new Guid("8fd0689d-5fd4-47c6-bb4d-3d38b624b9f2")
                        },
                        new
                        {
                            TagId = new Guid("ccc175b1-c0ba-438f-9ff5-6628bece730c"),
                            ArtworkId = new Guid("150d08d9-bdb5-478f-a6a2-88b207fc8cd5")
                        },
                        new
                        {
                            TagId = new Guid("8f47c5c7-1d60-43bd-b910-08c941ca1a43"),
                            ArtworkId = new Guid("150d08d9-bdb5-478f-a6a2-88b207fc8cd5")
                        },
                        new
                        {
                            TagId = new Guid("e7ffe31c-a60c-47a4-9c7c-14197683e390"),
                            ArtworkId = new Guid("f6b41168-339d-43be-bb15-0ac734e9beb6")
                        },
                        new
                        {
                            TagId = new Guid("e7ffe31c-a60c-47a4-9c7c-14197683e390"),
                            ArtworkId = new Guid("f7140316-7c2a-4876-b479-f2cbcafa8b61")
                        },
                        new
                        {
                            TagId = new Guid("2a2a8a52-b096-4788-a9f1-604bab8e2eec"),
                            ArtworkId = new Guid("150d08d9-bdb5-478f-a6a2-88b207fc8cd5")
                        },
                        new
                        {
                            TagId = new Guid("f3b21212-2734-409f-a7b3-d20aff4a8857"),
                            ArtworkId = new Guid("e49edb7b-926c-4ae6-9dab-4c81bbaf2b23")
                        },
                        new
                        {
                            TagId = new Guid("72db3ce9-f1ff-465f-9cef-78d496f4160d"),
                            ArtworkId = new Guid("f6b41168-339d-43be-bb15-0ac734e9beb6")
                        });
                });

            modelBuilder.Entity("ArtLite.Api.Entities.Artwork", b =>
                {
                    b.HasOne("ArtLite.Api.Entities.Creator", "Creator")
                        .WithMany("Artworks")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("ArtLite.Api.Entities.Image", b =>
                {
                    b.HasOne("ArtLite.Api.Entities.Artwork", "Artwork")
                        .WithMany("Images")
                        .HasForeignKey("ArtworkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artwork");
                });

            modelBuilder.Entity("ArtworkTag", b =>
                {
                    b.HasOne("ArtLite.Api.Entities.Artwork", null)
                        .WithMany()
                        .HasForeignKey("ArtworkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArtLite.Api.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ArtLite.Api.Entities.Artwork", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("ArtLite.Api.Entities.Creator", b =>
                {
                    b.Navigation("Artworks");
                });
#pragma warning restore 612, 618
        }
    }
}
